# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

secretGenerator:
- name: root-db-password
  literals:
  - password=secret
- name: db-password
  literals:
  - password=secret
configMapGenerator:
- name: pkg-mgr-config
  files:
  - deployments/.env
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: pkg-mgr-app
    path: deployments/kubernetes/volume-patch.yaml
resources:
- deployments/kubernetes/mariadb-deployment.yaml
- deployments/kubernetes/pkg-mgr-deployment.yaml