---
swagger: '2.0'
info:
  version: 1.0.0
  title: cURL Package Manager Server
  description: This application provides bash scripts for the installation of packages on different Linux distributions
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

parameters:
  pkg:
    name: pkg
    description: List of packages to be installed
    in: query
    type: string
    required: true
    minLength: 1
  pkg_update:
    name: pkg_update
    description: Specifies whether the update action has been requested
    in: query
    type: boolean
    required: false

responses:
  errorNotFound:
    description: The bash script was not found
  errorResponse:
    description: Error

paths:
  /pkgInstall:
    get:
      produces:
        - text/plain
      parameters:
        - $ref: "#/parameters/pkg"
        - $ref: "#/parameters/pkg_update"
      operationId: getScript
      responses:
        200:
          description: returns a bash script
          schema:
              type: string
              description: contains the bash instructions to install the desired package
        404:
          $ref: "#/responses/errorNotFound"
        default:
          $ref: "#/responses/errorResponse"